name: example
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  colorist_ui:
    path: ..
    version: any
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.0
  riverpod_annotation: ^4.0.0

dev_dependencies:
  build_runner: ^2.4.15
  custom_lint: ^0.8.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^4.0.0+1
  riverpod_lint: ^3.0.0

flutter:
  uses-material-design: true
