name: colorist_ui
description: "A Flutter library of UI components for an LLM codelab."
version: 0.2.5
repository: https://github.com/domesticmouse/colorist_ui

environment:
  sdk: ^3.8.0

dependencies:
  characters: ^1.3.0
  collection: ^1.19.0
  flutter:
    sdk: flutter
  flutter_markdown_plus: ^1.0.3
  flutter_riverpod: ^3.0.0
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  logging: ^1.3.0
  riverpod_annotation: ^3.0.0
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.4
  json_serializable: ^6.9.4
  mocktail: ^1.0.4
  riverpod_generator: ^3.0.0

flutter:
  uses-material-design: true
